[theme]
base = "light"
primaryColor = "#0F7B7E"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#EDF5F6"
textColor = "#102B37"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
